### ISSUE TITLE
Update AMI ids in instructions

### ISSUE THREAD

**Issue by JoshRosen** [amplab/training#114]
The instructions reference the training AMI id in a few places, but all of the ids disagree:

```
$ git grep ami-

_config.yml:AMI: ami-b70196de
launching-a-bdas-cluster-on-ec2.md:    ./spark-ec2 -i <key_file> -k <name_of_key_pair> -a ami-452f622c --copy launch amplab-training
launching-a-bdas-cluster-on-ec2.md:    ./spark-ec2 -i <key_file> -k <name_of_key_pair> -r us-west-1 -a ami-6ac4ee2f --copy launch amplab-training
```

We should use the correct the AMI id in _config.yml, then use that liquid template variable everywhere.

**Comment by shivaram** [comment]
Just to clarify we need two AMI IDs, `ami-452f622c` is the ampcamp3 AMI in us-east and `ami-6ac4ee2f` is the AMI in us-west.

**Comment by JoshRosen** [comment]
Ah, I forgot that the IDs differed across regions.

It looks like the Liquid template variables aren't processed in kramdown, and we aren't using them anywhere, so I may just remove them to avoid confusion.

**Comment by andyk** [comment]
Yeah we should definitely remove them if we aren't using them. Thanks for
catching this.
