### ISSUE TITLE
List of directories on AMI out of date

### ISSUE THREAD

**Issue by andyk** [amplab/training#12]
In the tutorial (under 5.1 Cluster Details), it lists:

``` text
ephemeral-hdfs: Hadoop installation.
hive: Hive installation
java-app-template: Some stand-alone Spark programs in Java
mesos: Mesos installation
mesos-ec2: A suite of scripts to manage Mesos on EC2
scala-2.9.2.final: Scala installation
scala-app-template: Some stand-alone Spark programs in Scala
spark: Spark installation
shark: Shark installation
streaming: Stand-alone program for Spark Streaming exercises
```

I'm using the following AMI, made by Shivaram: amplab-training (ami-6170e708)

I think the following changes need to be made to this list (in the training doc) to reflect the now updated directories on the AMI:
- hive -> hive-0.9.0-bin
- remove java-app-template
- remove mesos-ec2
- remove scala-app-template
- shark -> shark-0.2

Also, the directories that exist on the AMI currently but aren't in this list in the the training docs are:
- hadoop-mesos: [description goes here]
- kmeans: Template code for kmeans and featurization
- persistant-hdfs
- training: a repository of AMPLab training documents used to set up the AMI for this or other tutorials

**Comment by shivaram** [comment]
The final directory list

Infrastructure:
ephemeral-hdfs
scala-2.9.2
hive-0.9.0-bin
shark-0.2
spark
mesos

Useful scripts/documentation
mesos-ec2
spark-ec2
training

Templates for exercises
kmeans
streaming
java-app-template
scala-app-template

Don't need to explain ?
hadoop-mesos
persistent-hdfs

**Comment by shivaram** [comment]
Josh fixed this
