### ISSUE TITLE
Shark query stalls with no error logged

### ISSUE THREAD

**Issue by owenrh** [amplab/training#121]
Whilst attempting to run the first Shark query (after running the two create table statements), from http://ampcamp.berkeley.edu/big-data-mini-course/data-exploration-using-shark.html,  it just seems to stall without any error message.

The last few lines are shown below:

...
13/12/20 12:58:53 INFO cluster.ClusterScheduler: Adding task set 0.0 with 1 tasks
13/12/20 12:58:53 INFO cluster.ClusterTaskSetManager: Starting task 0.0:0 as TID 0 on slave 0: ip-10-183-144-167.ec2.internal (PROCESS_LOCAL)
13/12/20 12:58:53 INFO cluster.ClusterTaskSetManager: Serialized task 0.0:0 as 9317 bytes in 10 ms
13/12/20 12:58:55 INFO spark.MapOutputTrackerActor: Asked to send map output locations for shuffle 0 to ip-10-183-144-167.ec2.internal:50847
13/12/20 12:58:55 INFO spark.MapOutputTracker: Size of output statuses for shuffle 0 is 72 bytes

The Spark web console shows the following:
![screen shot 2013-12-20 at 13 01 21](https://f.cloud.github.com/assets/2006075/1790470/ea84ccf4-6976-11e3-9162-fa7b31a8c06d.png)

Any ideas? I've Google'd this without any joy.

**Comment by owenrh** [comment]
I guess the cluster got out of shape somehow. I restarted Spark on the master and slaves and it seems to work fine now. 

Just a glitch in The Matrix?!!

**Comment by rxin** [comment]
Thanks for reporting. EC2 clusters sometime have transient problems that are solved pretty quickly. ..
