### ISSUE TITLE
mesos-ec2 missing on AMI

### ISSUE THREAD

**Issue by andyk** [amplab/training#13]
Using AMI "amplab-training (ami-6170e708)"

I don't see mesos-ec2 directory, which tutorial has users interact with starting at the end of 5.1:

```
You can find a list of your 3 slave nodes in mesos-ec2/slaves:
    cat mesos-ec2/slaves

For stand-alone Spark programs, you will have to know the Spark cluster URL.
You can find that in mesos-ec2/cluster-url:
    cat mesos-ec2/cluster-url
```

Did this just get moved or was it deleted on purpose?

**Comment by shivaram** [comment]
I fixed this in a newer version of the ami. spark-ec2 has the latest version of the scripts right now, but masters,slaves,cluster-url, copy-dir are mirrored in both now
