### ISSUE TITLE
Port 4040 seems to be closed

### ISSUE THREAD

**Issue by mauricioalarcon** [amplab/training#139]
Per your instructions we should be able to connect to 
<code>http://<master_node_hostname>:4040</code>

But the port seems to be closed, one workaround that I used was create a ssh-tunnel

**Comment by pwendell** [comment]
Mind sending the master of your cluster?

**Comment by mauricioalarcon** [comment]
ec2-54-225-38-21.compute-1.amazonaws.com

**Comment by pwendell** [comment]
ah I figured it out - fixed.

**Comment by pwendell** [comment]
or rather - try again?
