### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by bmwshop** [amplab/training#157]
Tried to fllow the guide but no joy.. narrowed down to this:

aws ec2 run-instances --image-id ami-19474270 --count 1 --instance-type t2.micro  ...

A client error (InvalidAMIID.NotFound) occurred when calling the RunInstances operation: The image id '[ami-19474270]' does not exist

Is there a list of software that I could simply install myself on a standard image?

Thanks

**Comment by etrain** [comment]
Make sure you're running in the US East (N. Virginia) region - that AMI is not available in every region.

**Comment by bmwshop** [comment]
thank u :)
