### ISSUE TITLE
Try different ec2 instance types

### ISSUE THREAD

**Issue by shivaram** [amplab/training#25]
m2.xlarge  has only 2 cores and memory might be limited as well. Find out which works best for pyspark as well.

**Comment by shivaram** [comment]
m1.xlarge has 4 cores and 15G of memory. We will use 4 m1.xlarge slaves to get 16 cores + 60G of memory. This should be significantly better than 3 m2.xlarge slaves (6 cores + 52G of memory).

**Comment by shivaram** [comment]
Fixed text in https://github.com/amplab/training/commit/27d496bdee5cd329b4e4c7ebd1b75d393e27390b . Still need to time how long pyspark takes with this setup.

**Comment by shivaram** [comment]
1st run of pagecounts.count() took 220.580934466s with this setup. The next scan of the entire dataset enPages.count() took 389.531172087s  .

After caching, enKeyValuePairs.reduceByKey(lambda x, y: x + y, 1).collect() took 137.879609853s
(There were still some tasks which took 20-30s with caching. I am not sure why)

Does this sound good or should we add 4 cores with another m1.xlarge slave ?

**Comment by JoshRosen** [comment]
Are those numbers for PySpark?  How do they compare with the old timings?

**Comment by mateiz** [comment]
We should really aim for below 20 seconds on the second round. We can change it from enPages to frPages or something if necessary.

By the way, the cores on m1.xlarge are significantly slower than on m2. It might be worth going for m2. Or see whether we can make the data fit in enough c1 instances.

**Comment by shivaram** [comment]
Yes. These numbers are from pyspark. I am not sure what the old timings were, but I guess they were around 10 mins -- so this is much better. 

Also I was using the same build as we did for the Feb 5th dry run (mesos-spark master at 2d9eca). Will updating help ?

**Comment by mateiz** [comment]
BTW, in addition to what I mentioned above, one other option may be m3 instances with EBS volumes for /mnt and such. You'd have to set that up manually unfortunately, so it might be too much of a pain.

**Comment by shivaram** [comment]
So ignoring EBS-only instances, any instance with < 4 cores and cluster-compute instances, we have the following options: 

m1.xlarge: 15.00 GB, (4 cores x 2 units), 1690 GB (4x420 GB), $0.48 hourly
c1.xlarge:  7.00 GB, (8 cores x 2.5 units), 1690 GB (4x420 GB), c1.xlarge $0.58 hourly
m2.2xlarge: 34.20 GB, (4 cores x 3.25 units), 850 GB, $0.82 hourly

We need around 50GB of memory, so I guess the choices we have are:
- 5 m1.xlarge (4 slaves) => 60GB, 16 cores (32 EC2 cores)  = $2.4 hourly
- 6 m1.xlarge (5 slaves) => 75GB, 20 cores (40 EC2 cores)  = $2.87 hourly
- 8 c1.xlarge (7 slaves) => 56 GB, 56 cores (140 EC2 cores) = $4.63 hourly
- 4 m2.2xlarge(3 slaves) => 102 GB, 12 cores (39 EC2 cores) = $3.27 hourly

**Comment by mateiz** [comment]
6 m1.xlarge sounds best then, but what's the performance like compared to 4 m2.2xlarge? It may not be linear with EC2 cores.

In any case, it may be worth changing that Python tutorial from en to fr, or also adding a filter on date.

Matei

**Comment by shivaram** [comment]
Some timing numbers for pyspark from different setups. The time take seems to scale with the number of cores available i.e having more powerful cores doesn't seem to make a difference. Further the time taken for frPages seems to be the same as enPages. I think there are some constant overheads involved which seem to be independent of the data ? 

Anyways, since we don't have much time to debug this, I think we will just go with the 6 m1.xlarge setup.

6 m1.xlarge (5 slaves)
pagecount.count() - 186.77s
enPages.cache().count() - 324.65s
enPages.count() - 73.73s
frPages.cache().count() - 339.16s
frPages.count() - 77.8s

4 m2.2xlarge (3 slaves)
pagecount.count() - 276.980102326
enPages.cache().count() - 559.176
enPages.count() - 177.219533512
frPages.cache().count() - 587.421350653
frPages.count() -183.794678453

**Comment by mateiz** [comment]
6 m1.xlarge sounds good. In fact, it might be better to make it 7, since it won't cost that much.

**Comment by shivaram** [comment]
I think we'll stick with 6 m1.xlarge -- The total time to run all the python experiments will be 10-15 mins which I think should be okay.
