### ISSUE TITLE
Change "Intro to scala" to "Intro to Scala Shell [for Java Developers?]"

### ISSUE THREAD

**Issue by shivaram** [amplab/training#27]
Break it into two parts or make it shorter.
First part should be small and sufficient for cmd line exercises. Second part should be before ML with functions and stuff

**Comment by andyk** [comment]
Also, don't forget to update all (only one currently) links to this section when updating the section name.

**Comment by JoshRosen** [comment]
Is there some kind of automated link checker that we could use to detect broken links?  This would be useful for the Spark docs, too.  I tried one link checker, but it didn't handle certain types of links properly (like anchors).
