### ISSUE TITLE
Introduction to stand alone Spark programs

### ISSUE THREAD

**Issue by tdas** [amplab/training#28]
This section was removed. Its needs to be discussed whether this section (as a subsection to Spark section) should be kept or not. 

If not kept, then remove references to it from Spark Streaming intro and remove the only subsection in Spark

If kept, then put it back.

**Comment by andyk** [comment]
I put this section back in with wording to make it fit into the tutorial better. Basically making it clear that it is for reference and that we will come back to it later in the streaming section.
