### ISSUE TITLE
Check references to Mesos

### ISSUE THREAD

**Issue by JoshRosen** [amplab/training#33]
There are references to Mesos in the tutorial.  We should check to make sure that these are still relevant.

**Comment by shivaram** [comment]
We could change all mesos-ec2 references to spark-ec2 ... The cluster-url, slaves are all mirrored in both directories. Would this address this ?

**Comment by JoshRosen** [comment]
Yeah, that's fine.  I figured that it might be worth changing since the tutorial uses standalone mode now.
