### ISSUE TITLE
Add references to other Spark Documentation

### ISSUE THREAD

**Issue by andyk** [amplab/training#35]
We should maybe add a section at the end called "Where to go from here"

It can reference the Spark documentation, the examples that come with Spark, the the first AMP Camp, possibly some of the better blog posts, ...?

**Comment by andyk** [comment]
We should also provide a link to the Spark API documentation early on so that tutorial takers might be able to benefit by using it if they get stuck on something that they could answer using the API.

**Comment by pwendell** [comment]
Also consider referencing auto-completion in scala (e.g. holding down TAB
to see what methods are available). And using the help function in python
(e.g. help(my_rdd)) for similar list.
- Patrick
