### ISSUE TITLE
Make amplab/training-scripts repo public

### ISSUE THREAD

**Issue by andyk** [amplab/training#38]
Since as of 239312fc1faccdc8170881052f1881474a915bc0 we instruct people to clone/use the https://github.com/amplab/training-scripts repo, that repo now needs to be public.

**Comment by shivaram** [comment]
Note: We should also make github.com/amplab/training public as we checkout this repo on the AMI.

**Comment by andyk** [comment]
Shivaram, if you wanna just flip the switch on these repos to make them public, go ahead. Else I can.

**Comment by shivaram** [comment]
Flipped the switch !
