### ISSUE TITLE
On AMI, /root/kmeans is a symlink to /root/training/kmeans which doesn't exist

### ISSUE THREAD

**Issue by andyk** [amplab/training#40]
Maybe this has been fixed since I launched my cluster, but...

``` text
> ls -al /root/kmeans
lrwxrwxrwx 1 root root 21 Feb 24 22:20 /root/kmeans -> /root/training/kmeans
> ls -al /root/training/kmeans
ls: cannot access /root/training/kmeans: No such file or directory
```

**Comment by andyk** [comment]
Perhaps something didn't run when I spun up this cluster. I spun up another one and the directory does exist.

**Comment by shivaram** [comment]
I think this was the git clone bug Patrick pointed out last night. It was fixed in https://github.com/shivaram/spark-ec2/commit/b385ccdec41b6aaf3de8718f3ad54fd4d2f9a6c2
