### ISSUE TITLE
AMI has infinite symlinks inside of each folder

### ISSUE THREAD

**Issue by pwendell** [amplab/training#44]
e.g. the kmeans folder has a symlink that links back to kmeans

**Comment by shivaram** [comment]
I think I fixed this in https://github.com/shivaram/spark-ec2/commit/a94b9a713305e6915a9c7c47bf8b3ae1d9f5d467
Checking now with the new AMI

**Comment by shivaram** [comment]
Actually fixed in https://github.com/shivaram/spark-ec2/commit/1a5f97d1f12eaed774483ee5f4f8c073fb7687e9
