### ISSUE TITLE
Build a simple service to distribute hostname, keys

### ISSUE THREAD

**Issue by shivaram** [amplab/training#47]
Since pieces of paper or google docs doesn't work, I think we should try to build a simple service (say heroku?) which will take an email id, name as login and return ec2 hostname and keys for download. And then we can save the email id, hostname mapping in a database  etc.

Thoughts ?

**Comment by andyk** [comment]
Maybe some scripting in Google docs with a form? They actually have a
decent api.

**Comment by andyk** [comment]
I'm sure we can download a CSV file with the email of all registered attendees, so we could mail merge something to them or we could distribute the hostname to them using a similar strategy that we used today at the dry-run. For the actual event, they will still be all using the same key right?

**Comment by shivaram** [comment]
Yes - I think we would still ask all of them to use the same key to make distribution simple. We could either use the same key as the one used in dry run or generate a new one. I think either mail merge or read only spreadsheet should work, though mail merge might be better as we can send out key, hostname and instructions etc.

**Comment by andyk** [comment]
Shivaram and I got the a sweet mail merge system working today using google spreadsheet + google script + google doc (for writing an html text body)
