### ISSUE TITLE
Ask people to look at the per-job web UI during exercises

### ISSUE THREAD

**Issue by pwendell** [amplab/training#54]
Now that we have a UI - we should encourage people to use it! Also we need to open 33000 on the cluster.

**Comment by pwendell** [comment]
Also we should fix the hostnames so that the public hostname appears (if this is possible).

**Comment by JoshRosen** [comment]
@pwendell Where are private hostnames appearing?  The 0.8 UI may link to private EC2 hostnames in a couple of places, but that should be relatively easy to fix (we fixed this once before): https://spark-project.atlassian.net/browse/SPARK-833

**Comment by andyk** [comment]
We discussed this today at the AMP Camp meeting and we're going to switch out the screenshot and point them to 33000 and update the screenshot with that per-job webui too.

**Comment by JoshRosen** [comment]
If nobody else is working on this, I can switch out the screenshot in the "Data Exploration Using Spark" section and edit the text to point to the application UI (I'm in the middle of walking through the exercises right now).

If users use the application UI to track the progress of standalone jobs, then that UI will become unavailable once the standalone driver exits.  Do you think that this will be confusing to users?

**Comment by mateiz** [comment]
The UI has been moved to port 3030 in master FYI.. just be careful if you update.

**Comment by pwendell** [comment]
I think because the 3030 UI will disappear, it would actually be good to show/reference them both. For instance "Here is a cluster-wide UI and you can also get a UI for a running job here". Also, for the hostname issue, Shivaram just mentioned that, I didn't personally see it, so it could be totally fixed now. @JoshRosen , feel free to patch the docs, no one else is working on this now.

**Comment by shivaram** [comment]
Just another note -- I pulled on Spark master yesterday so the port is 3030 now and not 33000. 

Also it might be better to differentiate between the two UIs as one being a cluster status and the other being application status. This is because for the mesos exercises, the cluster UI will be 5050 for mesos, but the application UI will still be 3030.

**Comment by JoshRosen** [comment]
I just updated the docs with new screenshots.  Please take a look and feel free to make improvements.
