### ISSUE TITLE
Scala-specific note is confusing to Python users

### ISSUE THREAD

**Issue by arlofaria** [amplab/training#55]
This bit was confusing:

"Note that when we don’t specify a name for the result of a command (e.g. val enTuples above), a variable with name resN is automatically created."

I think that's referring to the Scala example only, not the Python example, right?

**Comment by andyk** [comment]
It isn't referring to the code box immediately above the text you're referencing, but rather to the code box above that, which contains (for Python):

```
>>> enTuples = enPages.map(lambda x: x.split(" "))
>>> enKeyValuePairs = enTuples.map(lambda x: (x[0][:8], int(x[3])))
```

...So it looks like both Scala and Python use the same variable name enTuples. I can see why it is a bit confusing though.

**Comment by arlofaria** [comment]
Hmm... would it be possible to have the document dynamically adjust 
parts of the text depending on which codetab (Scala or Python) is 
currently active?

When you say something like "(e.g. val enTuples above)" it's slightly 
confusing if you've been looking at the Python codetab that shows 
"enTuples =" and you're trying to figure out where this "val" business 
originated.

As noted, "above" actually means "two boxes above", which is also confusing.

Regardless, isn't the note about a variable being automatically named 
"resN" only applicable to Scala?  I don't think this happens in Python.  
Instead, I think the default variable for an interactive Python shell is 
the underscore character, right?

It's also slightly confusing toward the beginning of the Spark tutorial, 
when the document says:

When your count does finish running, it should return the following result:

|res: Long = 329641466|

That is only what you see for the Scala example.  If you run the Python 
example, the result does not include the bit about "res: Long = " and 
just displays the number.

Anyway, just mentioning these things in case it can help improve the 
tutorial for the upcoming camp.  I really enjoyed it and am excited to 
have a deeper look at Spark some day.

Thanks!
-arlo

**Comment by andyk** [comment]
Thanks a ton for responding Arlo. Sorry I didn't read though the section you were referring to more closely the first time. Your points are right now and addressing these things will make the exercises much more approachable to python users. Reopened this to track changes when one of us makes a pass to address it.
