### ISSUE TITLE
Various MLbase updates (that Ameet and Evan know about)

### ISSUE THREAD

**Issue by andyk** [amplab/training#58]
This is including:
- [ ] Tell users they need scala on their machines, make sure it works for Windows users.

**Comment by JoshRosen** [comment]
- [ ] Are there Scaladocs for the MLI classes, such as MLTable and MLRow?  It would be good to link to these.

**Comment by JoshRosen** [comment]
There are multiple bugs in the solution to the "Parameter Tuning" exercise:
- [x] The `learningRates` map function returns a constant (`lr` is never used):
  
  ``` scala
  val learningRates = List(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0, 1000.0)
  
  val models = learningRates.map({lr =>
     SVMAlgorithm(featurizedData, SVMParameters(learningRate=0.001, numIterations=100))
     })
  ```
- [x] It doesn't show how to compute `bestModel`:
  
  ``` scala
  val sortedParms = learningRates.zip(modelErrors)
  //Best model is the one with lowest error
  val bestModel = //
  ```
- [x] The same `featurizedData.numRows` optimization should be applied when computing the model errors:
  
  ``` scala
  val modelErrors = models.map(model => {
     val trainVsTest = featurizedData.map(r => MLRow(r(0), model.predict(r(1 until r.length))))
     trainVsTest.filter(r(0) != r(1)).numRows.toDouble/trainVsTest.numRows
     })
  ```

Additionally, this exercise may take a very long time to run: even if each model took 5 minutes to train, it would take close to an hour to train this many models.
