### ISSUE TITLE
Small bug in provided solution for Shark

### ISSUE THREAD

**Issue by mateiz** [amplab/training#70]
The question "How many hits are there on pages with Berkeley in the title throughout the entire period?" provides the following solution:

```
 select count(page_views) from wikistats_cached where page_name like "%berkeley%";
```

It should probably be `sum(page_views)`, not `count(page_views)`.

**Comment by MJJoyce** [comment]
Agreed, should be `sum(page_views)` not `count(page_views)`. Thanks Matei!
