### ISSUE TITLE
Newline missing in blinkdb code

### ISSUE THREAD

**Issue by balshor** [amplab/training#82]
Step 2 has the following text:

![screen shot 2013-08-29 at 3 27 00 pm](https://f.cloud.github.com/assets/64162/1053967/2675a40c-10fa-11e3-8edb-0cff1aa947cd.png)

The "OK" belongs on a new line following the semi-colon.  As is, it may be interpreted as part of the text that the user is supposed to enter.

**Comment by henryem** [comment]
Thanks, it's fixed now.
