### ISSUE TITLE
Add FAQ for "table already exists" error to BlinkDB exercise

### ISSUE THREAD

**Issue by balshor** [amplab/training#83]
If users have followed the exercises sequentially on the same cluster, they will already have the wikistats table metadata from the Hive exercise when they do the BlinkDB exercise.  This will cause the following error:

FAILED: Error in metadata: AlreadyExistsException(message:Table wikistats already exists)
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask

Some additional guidance for dealing with this scenario (just ignore? drop table and recreate? something else?) would make a good FAQ.

**Comment by henryem** [comment]
Thanks.  Actually there is a similar issue in the Shark exercises if you kill your shell and restart the exercises.  The fix is to drop all tables you've created.  I'll add instructions on both Shark and BlinkDB.
