### ISSUE TITLE
update samplewidth text (blinkdb)?

### ISSUE THREAD

**Issue by jowens** [amplab/training#88]
```
blinkdb> create table wikistats_sample_cached as select * from wikistats_cached samplewith 0.01;
Sample With Operator Invoked with probability = 0.01
Sample With Operator Invoked with probability = 0.01
Moving data to: hdfs://ec2-54-226-130-103.compute-1.amazonaws.com:9000/user/hive/warehouse/wikistats_sample_cached
OK
Time taken: 20.859 seconds
```

(Mine has the "Sample With operator  ..." text in addition to what you have there.) Now, why is this printed twice?

**Comment by sameeragarwal** [comment]
@jdowens: Yes, it should just be displayed once. Displaying it twice was an unfortunate bug introduced due to the need of displaying an INFOLog statement to the user for the purpose of AMP Camp. I will revert this back in the main repo. Thanks!
