### ISSUE TITLE
Strata tutorial still has ampcamp repo

### ISSUE THREAD

**Issue by andyk** [amplab/training#9]
Stata docs still say to use `git clone git://github.com/amplab/ampcamp.git`

Shouldn't they now say `git clone https://github.com/amplab/training-scripts`

**Comment by shivaram** [comment]
I think we can get rid of the launching a cluster instructions. We don't need that for the dry run or the strata tutorial

**Comment by andyk** [comment]
We didn't get rid of it, but we did move it into a different page (see it in its current version at http://www.cs.berkeley.edu/~andyk/big-data-crashcourse/launching-a-cluster.html). So we'll probably want to update this other page now, right?

**Comment by shivaram** [comment]
Fixed the repo in https://github.com/amplab/training/commit/239312fc1faccdc8170881052f1881474a915bc0
The key names are still ampcamp-all.pem, but I guess we'll let that be.
