### ISSUE TITLE
BlinkDB exercise needs a step to set the sample and dataset sizes

### ISSUE THREAD

**Issue by elicollins** [amplab/training#90]
Otherwise the example fails with the following:

blinkdb> select approx_count(1) from wikistats_sample_cached;
FAILED: Hive Internal Error: Sample Size not set
Please use set blinkdb.sample.size=<rows> to set Sample Size
FAILED: Hive Internal Error: Dataset Size not set
Please use set blinkdb.dataset.size=<rows> to set Sample Size

**Comment by sameeragarwal** [comment]
Eli, we do state these instructions in step 5 of the BlinkDB exercise: http://ampcamp.berkeley.edu/3/exercises/blinkdb.html. Do you think they should be made more explicit?

**Comment by pwendell** [comment]
Hey @sameeragarwal  - I think @elicollins was using an older version of the docs (I chatted with him), so probably we can close this.

**Comment by sameeragarwal** [comment]
Perfect. Thanks!
